spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pegasagro
    username: pegasagro
    password: pegasagro
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate.ddl-auto: update
    generate-ddl: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB